---
title: "Obective 1"
author: "S. Sunoj"
date: "2022-09-13"
output:
  html_document: default
  pdf_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Load packages
```{r, warning= FALSE, message=FALSE}

rm(list = ls())
gc()

library(sf)
library(dplyr)
library(plyr)
library(ggplot2)
library(plotly)
library(scales)
library(tictoc)
library(here)

print("Packages loaded successfully!")

source("exponential_model_functions.R")

```


# Load data

```{r, message=FALSE}

# Load training data
load("../RData/Strips_NoOutlier_df.RData", verbose = TRUE)

# Load validation data
load("../RData/WF_validation_df.RData", verbose = TRUE)

colnames(all_strips_dat)
```

# Plot one field of training and testing field
```{r}
# "DMD_GH1" "SLS_ABH" "SLS_NS"  "PSF_12"  "PSF_111" "SSF_66"  "SSF_121" "SSF_202"

subfield <- "DMD_GH1"

trainingdata <- all_strips_dat %>% 
  filter(Fieldname == subfield) %>% 
  filter(Week == 29) %>% 
  droplevels()

testingdata <- WF_validation_df %>% 
  filter(Fieldname == subfield) %>% 
  filter(Week == 29) %>% 
  droplevels()

cat(" (Training) Dimension of strips data = ", dim(trainingdata),"\n")
cat(" (Testing) Dimension of WF data without strips = ", dim(testingdata))
```

# DMD_GH1
```{r, figures-side, fig.show="hold", out.width="50%"}
par(mar = c(4, 4, .1, .1))
plot(st_as_sf(trainingdata)["Yield.Mg.ha"], border = "transparent", main = "Training data - Only strips")
plot(st_as_sf(testingdata)["Yield.Mg.ha"], border = "transparent", main = "Testing data - Whole field without strips and percentile data")

```

# Exponential model fitting with an example field
```{r}
# "DMD_GH1" "SLS_ABH" "SLS_NS"  "PSF_12"  "PSF_111" "SSF_66"  "SSF_121" "SSF_202"

subfield <- "DMD_GH1"

trainingdata <- all_strips_dat %>% 
  filter(Fieldname == subfield) %>% 
  # filter(Week == 35) %>% 
  droplevels()

testingdata <- WF_validation_df %>% 
  filter(Fieldname == subfield) %>% 
  # filter(Week == 35) %>% 
  droplevels()


if (!exists("results_df")){
  results_df <- data.frame()
}

vi_names <- c("NDVI", "GNDVI", "EVI2", "SR", "EXG", "TGI", "GCVI")
week_no <- unique(trainingdata$Week)

tic()
cat("Processing... \n")
for (i in 1:length(vi_names)){
  cat("Vegetation index = ", vi_names[i],"\n")
    for (j in 1:length(week_no)){
      
      cat("Week = ", week_no[i],"\n")
      # Subset the data
      trainingdata <- all_strips_dat %>% 
        filter(Fieldname == subfield) %>% 
        filter(Week == week_no[j]) %>%
        droplevels()

      testingdata <- WF_validation_df %>%
        filter(Fieldname == subfield) %>%
        filter(Week == week_no[j]) %>%
        droplevels()
      
      # Fit exponential model      
      mod_fit <- myexpfit("Yield", vi_names[i], trainingdata)
      
      # Evaluate model performance by RMSE
      mod_rmse <- getRMSE(mod_fit, "Yield", vi_names[i], testingdata)
      
      # Creating a list to be stored as an entry in a table format 
      text_imp <- c(subfield, week_no[j], vi_names[i], as.numeric(mod_fit[1]), as.numeric(mod_fit[2]), 
                    as.numeric(mod_fit[3]), as.numeric(mod_rmse[1]), as.numeric(mod_rmse[2]),
                    as.numeric(mod_rmse[3]))

      col_names <- c("Fieldname", "Week", "VI", "a_coeff", "b_coeff",
                     "R2", "RMSE", "NRMSE", "MAE")
      # 
      # colnames(results_df) <- col_names
      results_df <- rbind(results_df, text_imp)

    }
}

colnames(results_df) <- col_names

toc()

# Save the results tp a CSV file
# write.csv(results_df, "PartA_and_B_results.csv", row.names = FALSE)

```


# Load data for plotting Figure 2 in manuscript
```{r}

# load("PartA_and_B_results.RData", verbose = TRUE)

results_df <- read.csv("../RData/PartA_and_B_results.csv")

```

```{r}

si_df <- results_df %>% 
  filter(Unit == "SI") %>% 
  filter(Week == "35") %>%
  droplevels()

unique(si_df$Fieldname)

missing_df <- results_df %>%
  filter(Fieldname == "PSF_111") %>%
  filter(Unit == "SI") %>%
  filter(Week == "34") %>%
  droplevels()

si_df <- rbind(si_df, missing_df)
unique(si_df$Fieldname)

si_df$Fieldname <- factor(si_df$Fieldname, levels = c("PSF_12", "PSF_111", "SSF_66", "SSF_121", "SSF_202",
                                                      "SLS_ABH", "SLS_NS", "DMD_GH1"))


si_df$VI <- factor(si_df$VI, levels = c("NDVI", "EVI2", "GNDVI", "GCVI", "SR", "EXG", "TGI"))

grain_df <- si_df %>% 
  filter(Fieldname == "DMD_GH1" | Fieldname == "SLS_ABH" | Fieldname == "SLS_NS") %>%
  droplevels()

grain_plt <-  ggplot(grain_df, aes(x = Fieldname, y = as.numeric(RMSE), fill = VI)) + 
  geom_bar(stat='identity', color = "black", size = 0.4, position=position_dodge(), width = 0.7) + geom_text(aes(label= paste0(round(as.numeric(NRMSE),1), " %"), group = VI, angle = 90, vjust = 0.5, hjust = 1.2),position = position_dodge(width = 0.7), size = 3.2) + 
  # facet_wrap(~Type) + 
  theme_bw() + 
  # xlab("Vegetation indices") + 
  ylab("Root mean square error (RMSE, Mg/ha)") +
  scale_fill_manual(values = c("#dededd", "#eedd89", "#bbcc32", "#ffaabc", "#ef8766", "#99ddff", "#77aadd")) +
    scale_y_continuous(limit = c(0.0, 1.6), breaks = seq(0.0, 1.6, 0.2), expand = expansion(mult = c(0, 0.02))) + 
  # theme(legend.position = "none")+
  labs(fill = "Vegetation indices") + 
  theme(axis.text.x = element_blank(),
        axis.text.y = element_text(size = 12, color = "black"),
        axis.title = element_blank(),
        axis.ticks.x = element_blank(),
        panel.grid = element_blank(), 
        legend.text = element_text(size = 12, color = "black"), 
        legend.title = element_text(size = 12, face = "bold"), 
        panel.border = element_rect(colour = "black", fill=NA, size=0.75))

grain_plt

# ggsave("Grain_RMSE_plot.png", width = 10, height =3, unit = "in")
```


```{r}
silage_df <- si_df %>% 
  filter(Fieldname != "DMD_GH1" & Fieldname != "SLS_ABH" & Fieldname != "SLS_NS") %>%
  droplevels()

silage_df$Fieldname <-
  factor(
    silage_df$Fieldname,
    levels = c("PSF_111", "PSF_12", "SSF_121", "SSF_202", "SSF_66"))


silage_plt <-  ggplot(silage_df, aes(x = Fieldname, y = as.numeric(RMSE), fill = VI)) + 
  geom_bar(stat='identity', color = "black", size = 0.4, position=position_dodge(), width = 0.7) +   geom_text(aes(label= paste0(round(as.numeric(NRMSE),1), " %"), group = VI, angle = 90, vjust = 0.5, hjust = 1.2),position = position_dodge(width = 0.7), size = 3.2) + 
  # facet_wrap(~Type) + 
  theme_bw() + 
  # xlab("Vegetation indices") + 
  ylab("Root mean square error (RMSE, Mg/ha)") +
  scale_fill_manual(values = c("#dededd", "#eedd89", "#bbcc32", "#ffaabc", "#ef8766", "#99ddff", "#77aadd")) +
  # scale_fill_manual(values = c("#E10000", "#FFB383", "#585959", "#C0C0C0", "#00A210", "#9BE186", "#8FAADC")) +
  scale_y_continuous(limit = c(0.0, 8.0), breaks = seq(0.0, 8.0, 1.0), expand = expansion(mult = c(0, 0.02))) + 
  theme(legend.position = "none")+
  theme(axis.text.x = element_blank(),
        axis.text.y = element_text(size = 12, color = "black"),
        axis.title = element_blank(),
        axis.ticks.x = element_blank(),
        panel.grid = element_blank(), 
        panel.border = element_rect(colour = "black", fill=NA, size=0.75))

silage_plt

# ggsave("Silage_RMSE_plot.png", width = 10, height =6, unit = "in")


# gridExtra::grid.arrange(grain_plt, silage_plt)

# ggplotly(plt)

```


# Combine plots and save
```{r}
library(cowplot)

ggdraw() +
  draw_plot(silage_plt, x = 0.02, y = 0.5, width = 0.97, height = .48) +
  draw_plot(grain_plt, x = 0, y = 0, width = .88, height = .48)
  # draw_plot(bp, x = 0, y = 0, width = 1, height = 0.5) +
  # draw_plot_label(label = c("A", "B", "C"), size = 15,
  #                 x = c(0, 0.5, 0), y = c(1, 1, 0.5))

# ggsave("PartA_plot.png", width = 8.5, height = 6.2, unit = "in")

```



